version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always
  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://db:5432/shop_db -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    links:
      - db
  app:
    image: vladsmirn289/goodsshop
    container_name: GoodsShop
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
      - flyway